### ISSUE TITLE
Unable to filter on missing/empty label

### ISSUE THREAD

**Issue by nkilzer** [VictoriaMetrics/VictoriaMetrics#137]
**Versions**
VictoriaMetrics (VM): `1.23.0` (DockerHub: `victoriametrics/victoria-metrics:v1.23.0`)
 * correction: we had not applied the staged update to 1.23.0 - I will retest and update the issue if it provides different results
 * correction: the results on 1.23.0 are the same

Prometheus: `v2.11.1` (DockerHub: `prom/prometheus:v2.11.1`)
Grafana: `v6.2.5` (DockerHub: `grafana/grafana:6.2.5`)
K8S: `1.14` (Azure AKS)

**Problem**
When executing a query in Prometheus, it is possible to query metrics where a label is not set by explicitly querying equality with the empty string:

```container_cpu_usage_seconds_total{namespace="qa",container=""}```

Which returns series like the following, which are basically the aggregate per-pod CPU totals:

```
container_cpu_usage_seconds_total{cpu="total",instance="node-00",job="k8s-cadvisor",namespace="qa",pod="app1-6f59f887b6-fs75s",region="eastus"}	36.736427425
container_cpu_usage_seconds_total{cpu="total",instance="node-01",job="k8s-cadvisor",namespace="qa",pod="app2-7496fdcdf7-zjn96",region="eastus"}	944.299937648
container_cpu_usage_seconds_total{cpu="total",instance="node-01",job="k8s-cadvisor",namespace="qa",pod="app3-648b7497dc-frhjw",region="eastus"}	462.068806962
container_cpu_usage_seconds_total{cpu="total",instance="node-01",job="k8s-cadvisor",namespace="qa",pod="app4-5877d77978-w8zr5",region="eastus"}	43.648966459
container_cpu_usage_seconds_total{cpu="total",instance="node-01",job="k8s-cadvisor",namespace="qa",pod="app5-674f77c649-q9z7t",region="eastus"}	23.96378955
container_cpu_usage_seconds_total{cpu="total",instance="node-01",job="k8s-cadvisor",namespace="qa",pod="app6-c74bd56f6-cqjtf",region="eastus"}	38.8601286
container_cpu_usage_seconds_total{cpu="total",instance="node-02",job="k8s-cadvisor",namespace="qa",pod="app7-7f9f469675-flxr6",region="eastus"}	34.73319896
container_cpu_usage_seconds_total{cpu="total",instance="node-02",job="k8s-cadvisor",namespace="qa",pod="app8-7c7b6c984f-rq85z",region="eastus"}	879.205477289
```

This works in both the Prometheus built-in graph editor, and via an associated Grafana instance.

However, running the same query in VM results in no results returned (not an error, just nothing displayed in the Grafana UI). I've tried most combinations I can think of to select an empty string (e.g. `container=""`, `container=~"^$"`, `container!~"^.+$"`, etc.).

These results are reproducible via the PromQL query API directly. I can provide the JSON responses if necessary though - the VM one contains nothing in the `result` array field.

I'm not sure if the discrepancy is due to Prometheus preserving the empty labels in some fashion, but dropping them during a remote write, or if VM is actually dropping the empty labels before storing, or if it's a quirk of the query processing in VM.

The series do exist in VM - when querying without the filter, they're returned and graphable and look right, so I'm not sure where it's getting lost.

**Use Case**
This is currently affecting use cases where we want to join to another query to determine relative weights of things, or attach K8S pod labels from the label scraping job that runs separately (for display). The left side of a query like `container_cpu_usage_seconds_total * on(pod,namespace) group_right kube_pod_labels` ends up containing duplicate sequences for the matching expression because we want the top-level results only, but the per-container results are included. I have tried filtering the left-hand side for a negative regex match like `container_cpu_usage_seconds_total{namespace="qa",container!~"^.+$"} * on (namespace,pod) group_right(instance,node) kube_pod_labels` to find only those series with a `container` label that contained no text, but that didn't seem to work either (all of the unwanted series have something in the `container` label value). Our current workaround is that all of our critical containers of interest share a few container names, and don't have sidecars of note, so we don't need the pod-level usage at this time.

**Additional Config**
The remote write config is basically identical to the VM sample, and does not have any relabel configs. The external labels just apply a `cluster` and `vm_cluster` label to distinguish series from different K8S environments:
```
global:
  scrape_interval: 30s
  external_labels:
    cluster: "%%CLUSTER_NAME%%"
    vm_cluster: "%%CLUSTER_NAME%%"
remote_write:
  - url: "%%VM_EP%%/api/v1/write"
    queue_config:
      max_samples_per_send: 10000
      max_shards: 100
```

**Source Metrics**
The raw metric lines scraped from the cAdvisor for one node from the above sample are below:
```
# HELP container_cpu_usage_seconds_total Cumulative cpu time consumed in seconds.
# TYPE container_cpu_usage_seconds_total counter
container_cpu_usage_seconds_total{container="",container_name="",cpu="total",id="/",image="",name="",namespace="",pod="",pod_name=""} 335101.037798236 1564468532249
container_cpu_usage_seconds_total{container="",container_name="",cpu="total",id="/kubepods/burstable/pod4365631c-a6a6-11e9-ab62-1e1b3a54f43b",image="",name="",namespace="int",pod="app2-6d6dfbf45f-gwrv7",pod_name="app2-6d6dfbf45f-gwrv7"} 839.496661322 1564468541245
container_cpu_usage_seconds_total{container="",container_name="",cpu="total",id="/kubepods/burstable/pod9205e218-b21a-11e9-91fd-e2a17f162769",image="",name="",namespace="qa",pod="app1-6f59f887b6-fs75s",pod_name="app1-6f59f887b6-fs75s"} 37.00281201 1564468525475
container_cpu_usage_seconds_total{container="POD",container_name="POD",cpu="total",id="/kubepods/burstable/pod4365631c-a6a6-11e9-ab62-1e1b3a54f43b/f3fab78684ac4ec96cbb4456e6d0d8dc07fab9c4fc82f0210620a6c5d7996bce",image="k8s.gcr.io/pause-amd64:3.1",name="k8s_POD_app2-6d6dfbf45f-gwrv7_int_4365631c-a6a6-11e9-ab62-1e1b3a54f43b_0",namespace="int",pod="app2-6d6dfbf45f-gwrv7",pod_name="app2-6d6dfbf45f-gwrv7"} 0.022739084 1564468527800
container_cpu_usage_seconds_total{container="POD",container_name="POD",cpu="total",id="/kubepods/burstable/pod9205e218-b21a-11e9-91fd-e2a17f162769/d3ce2d3f9d1c76126f6211769f3ef6c97c5bfae6345a23d5573d79c1170d2fa0",image="k8s.gcr.io/pause-amd64:3.1",name="k8s_POD_app1-6f59f887b6-fs75s_qa_9205e218-b21a-11e9-91fd-e2a17f162769_0",namespace="qa",pod="app1-6f59f887b6-fs75s",pod_name="app1-6f59f887b6-fs75s"} 0.02438505 1564468540952
container_cpu_usage_seconds_total{container="app",container_name="app",cpu="total",id="/kubepods/burstable/pod4365631c-a6a6-11e9-ab62-1e1b3a54f43b/1564b1164891c2273696b4825d73ba7dc5280053a9fbe6555a7947e7fc035f9b",image="<private.registry.io>/app2@sha256:<SHA>",name="k8s_app_app2-6d6dfbf45f-gwrv7_int_4365631c-a6a6-11e9-ab62-1e1b3a54f43b_0",namespace="int",pod="app2-6d6dfbf45f-gwrv7",pod_name="app2-6d6dfbf45f-gwrv7"} 839.469938941 1564468533470
container_cpu_usage_seconds_total{container="app",container_name="app",cpu="total",id="/kubepods/burstable/pod9205e218-b21a-11e9-91fd-e2a17f162769/dff6946ae866f336226b913981b157f34ad451084abb51ecfe2cd325fc3abba5",image="<private.registry.io>/app1@sha256:<SHA>",name="k8s_app_app1-6f59f887b6-fs75s_qa_9205e218-b21a-11e9-91fd-e2a17f162769_0",namespace="qa",pod="app1-6f59f887b6-fs75s",pod_name="app1-6f59f887b6-fs75s"} 36.986376991 1564468537549
```

Thanks!

**Comment by valyala** [comment]
@nkilzer , thanks for the bug report. The issue has been confirmed and will be fixed in the near future

**Comment by valyala** [comment]
@nkilzer , could you build VictoriaMetrics from the commit a77e88db7db6f94cbb9cf9a1d14173dfae1fa388 and verify whether the issue has been fixed? See [instructions on how to build from sources](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/README.md#how-to-build-from-sources).

**Comment by valyala** [comment]
oops, the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/a77e88db7db6f94cbb9cf9a1d14173dfae1fa388 contained a typo, so build VictoriaMetrics from the next commit - c14fd6c43f6c90e7aca296b083423004000297a5

**Comment by nkilzer** [comment]
@valyala - Thanks for the fast turnaround - the issue is indeed corrected in c14fd6c (built as a docker image, and deployed to our cluster). I also tetsted 3a38b23 (because I forgot to wind the source tree back before building the first time) and it remains corrected there.

**Comment by valyala** [comment]
Closing the bug. It must be fixed in [v1.23.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by vissible** [comment]
I got the same issue with v1.33.0.

**the query:**
```
container_cpu_usage_seconds_total{image=~"",systemd_service_name="",namespace="",kubernetes_io_hostname=~"k8s-node01.teambition.corp"}
```

**by Prometheus built-in graph:**
```
container_cpu_usage_seconds_total{cpu="total",job="kubernetes-cadvisor",kubernetes_io_hostname="k8s-node01.teambition.corp",usage="monitoring2"}   117783.208311443
```
**by VM query API directly:**
```
curl "127.0.0.1:8428/api/v1/query_range?query=container_cpu_usage_seconds_total%7Bimage%3D~%22%22%2Csystemd_service_name%3D%22%22%2Cnamespace%3D%22%22%2Ckubernetes_io_hostname%3D~%22%5Ek8s-node01%5C%5C.teambition%5C%5C.corp%24%22%7D&start=1581042960&end=1581043260&step=15"

{"status":"success","data":{"resultType":"matrix","result":[{"metric":{"__name__":"container_cpu_usage_seconds_total","cpu":"total","job":"kubernetes-cadvisor","kubernetes_io_hostname":"k8s-node01.teambition.corp","prom_name":"prometheus-core2","usage":"monitoring2"},"values":[[1581042960,"1787.5432052819"],[1581042975,"0.00187057"],[1581042990,"9185.87249478"],[1581043005,"394.677544761"],[1581043020,"9187.09768157"],[1581043035,"4049.9363711449"],[1581043050,"14.989231696"],[1581043065,"1788.215170405"],[1581043080,"0.010330897"],[1581043095,"0.004733176"],[1581043110,"84322.99352912"],[1581043125,"16.638361994"],[1581043140,"14.995519119"],[1581043155,"3948.3919790039"],[1581043170,"5314.17335166"],[1581043185,"3948.964195236"],[1581043200,"83920.51321686"],[1581043215,"395.114773846"],[1581043230,"9195.33174397"],[1581043245,"395.132010579"],[1581043260,"84385.87600249"]]}]}}
```

**Comment by valyala** [comment]
@vissible , could you provide more details about the issue you encounter? It looks like the original issue isn't related your issue, since in your case VictoriaMetrics correctly returns the same time series as Prometheus. This time series doesn't contain `image`, `systemd_service_name` and `namespace` labels as requested by the query. The time series returned by VictoriaMetrics contains an additional label - `"prom_name":"prometheus-core2"` . It is likely the label is from `external_labels` section inside Prometheus configuration.

**Comment by vissible** [comment]
@valyala, please refer to #312

**Comment by tekert** [comment]
I think this is still a problem for http requests against `http://vm:8428/api/v1/series` endpoint or other endpoints using `match[]`, 
I pushed some metrics without a instance label, i can see them in the web ui using: `{instance=""}`

But if I query using this endpoint, no data is returned.
```
curl -g 'http://<vm>:8428/api/v1/series?' --data-urlencode 'match[]={instance=""}'
{"status":"success","data":[]}
```
