### ISSUE TITLE
Inconsistency in data visualization from VM

### ISSUE THREAD

**Issue by JogiInnov** [VictoriaMetrics/VictoriaMetrics#166]
**90 days data showing on grafana but when selected for shorter period data not showing**

**To Reproduce**
Provide custom time range like 4 weeks and data is missing. 
Time range with 90 days working fine.
Note: We've used backfiling to import bulk data.
Note: We've tried deleting cache directory. and VM restart.

**Expected behavior**
Data should be available for both the time ranges.

**Screenshots**
1.) with 90days range:
![image](https://user-images.githubusercontent.com/47975052/63849830-77a15680-c9b0-11e9-974f-9825afa2027c.png)

2.) with 30days range:
![image](https://user-images.githubusercontent.com/47975052/63849847-812abe80-c9b0-11e9-8375-3bf6e1a7e051.png)

**Version**
The line returned when passing `--version` command line flag to binary. For example:
```
$ ./victoria-metrics-prod --version
-20190826-100646-heads-master-0-g2fc157f
```

**Additional context**
Add any other context about the problem here such as error logs, `/metrics` output, screenshots from [the official Grafana dashboard for VictoriaMetrics](https://grafana.com/dashboards/10229).

**Comment by valyala** [comment]
Try stopping VictoriaMetrics, then deleting the cache, then starting VictoriaMetrics again. The `cache` folder under `-storageDataPath` directory must be removed when VictoriaMetrics is stopped. Otherwise it will be re-created on VictoriaMetrics shutdown.

**Comment by JogiInnov** [comment]
Thanks @valyala issue resolved by following your instructions.

**Comment by valyala** [comment]
Then closing the issue.

**Comment by medvedik** [comment]
Hi,

I have very simillar issue. On 90d interval the return array from VM is empty. When I change interval to 6 months or 30 days (in Grafana) data are returned properly.

Clearing cache does not resolve the problem this time, although it helped me and resolved the issue last time (3 month ago).

I tried versions "v1.69.0" (victoria-metrics-20211108-135302-tags-v1.69.0-0-g69e655ba7), v1.66.2" with the same results.

Query which returns empty dataset:
curl -G 'http://192.168.1.105:8428/api/v1/query_range?query=node_memory_MemAvailable_bytes\{instance=~"192\\.168\\.1\\.109:9100"\}&start=1630418400&end=1638198000&step=3600&timeout:"30s"'

I tried some modifications and these queries are working:
- without instance label
curl -G 'http://192.168.1.105:8428/api/v1/quelable_bytes&start=1630418400&end=1638198000&step=3600&timeout:"30s"'
- increased step
curl -G 'http://192.168.1.105:8428/api/v1/query_range?query=node_memory_MemAvailable_bytes\{instance=~"192\\.168\\.1\\.109:9100"\}&start=1630418400&end=1638198000&step=360000&timeout:"30s"'

Thank you in advance,

Vit Bartunek
