### ISSUE TITLE
Very high memory usage after restart

### ISSUE THREAD

**Issue by Alexul** [VictoriaMetrics/VictoriaMetrics#2007]
**Describe the bug**
After Victoria restarts/version upgrades Victoria uses all the available mem on start, starving the os...

**To Reproduce**
stop Victora/start Victoria

**Expected behavior**
some initial spike of load on catching up to scrapers

version 1.70.0, with maxConcurrentInserts=48 in 96 cores

<img width="245" alt="Screen Shot 2021-12-26 at 10 00 37" src="https://user-images.githubusercontent.com/10867201/147402685-18df6185-d6f3-44cf-ac11-f01a844f2a77.png">

**Comment by Alexul** [comment]
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7776717/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7776718/mem.pprof.txt)

**Comment by Alexul** [comment]
Also mem usage stays elevated and reducing after removing all the queries load and almost all the writers (to make it possible to just start)
<img width="1352" alt="Screen Shot 2021-12-26 at 12 32 14" src="https://user-images.githubusercontent.com/10867201/147405747-f39ac08c-204b-474a-8ec7-bef81cf0b342.png">
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7776865/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7776866/mem.pprof.txt)

**Comment by YuriKravetc** [comment]
Hi,
Can you also attach the graphs from Troubleshooting part, and disc usage please?

**Comment by Alexul** [comment]
I hope this works [https://snapshot.raintank.io/dashboard/snapshot/OHXuuxlYlKcz7Lj54Vle5Pn1PJnduzwf?orgId=2](https://snapshot.raintank.io/dashboard/snapshot/OHXuuxlYlKcz7Lj54Vle5Pn1PJnduzwf?orgId=2)

**Comment by YuriKravetc** [comment]
It works but troubleshooting part is missing, share it, please.

**Comment by Alexul** [comment]
let try again https://snapshot.raintank.io/dashboard/snapshot/I76S4O24QkW6S0ADH1xzRqucA0XzIk31

**Comment by YuriKravetc** [comment]
@valyala Can you advise on it, please?

**Comment by Alexul** [comment]
on related note, how can cache size be bigger than limit?
<img width="689" alt="Screen Shot 2022-01-10 at 14 39 29" src="https://user-images.githubusercontent.com/10867201/148767458-1d457248-2d4d-4254-a413-af78ecb0c3c5.png">

**Comment by valyala** [comment]
The provided memory profiles show that the majority of the allocated memory was used by `indexdb` cache, which contains unpacked data blocks in memory. This cache could grow beyond the configured limits via `-memory.allowedPercent` and/or `-memory.allowedBytes` because the limits were applied independently per each data part. If `indexdb` contains many data parts, then the summary cache size for all the data parts could exceed the configured limits.

The issue should be fixed in the commit 9797c928efa3412aa76bbc9941f0c46751bbaf3f , which applies global limits to `indexdb` cache. It should prevent from possible OOMs in the case if `indexdb` contains many data parts (the number of data parts in indexdb can be monitored via `vm_parts{type="indexdb"}` metric).

@Alexul, could you try VictoriaMetrics docker image from the tag `heads-public-single-node-0-g9797c928e` (e.g. `docker.io/victoriametrics/victoria-metrics:heads-public-single-node-0-g9797c928e` ) and check whether it fixes the issue?

**Comment by Alexul** [comment]
Thanks, confirming heads-public-single-node-0-g9797c928e memory limits working, but that version just couldn't start/catch up with write load for me
<img width="1383" alt="Screen Shot 2022-01-20 at 21 10 09" src="https://user-images.githubusercontent.com/10867201/150406681-ad972dbd-714b-461f-86e6-3df5736d331f.png">
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7907900/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7907901/mem.pprof.txt)

**Comment by valyala** [comment]
It looks like the provided profiles were collected from `v1.70.0` instead of `heads-public-single-node-0-g9797c928e`.

Could you run the updated Docker image from `heads-public-single-node-0-gede93469e` and collect cpu + mem profiles from it? It would be great if you could share graphs for the the following queries on the time range covering the previous version of victoriametrics (I assume this is `v1.70.0`. If not, then please post the previous version number) and the updated docker image:

```
vm_cache_entries{type=~"indexdb/.+"}
vm_cache_size_bytes{type=~"indexdb/.+"}
rate(vm_cache_misses_total{type=~"indexdb/.+"}) / rate(vm_cache_requests_total{type="indexdb/.+"})
```

Could you also try running the previous versions of VictoriaMetrics and find the latest one, which is free from this issue?

**Comment by Alexul** [comment]
Ok, recreated with `heads-public-single-node-0-gede93469e`, still cannot start. The change is from 1.70.0->gede93469e and i removed -memory.allowedPercent=30 to get a default value
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7915814/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/7915815/mem.pprof.txt)


`2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:12 build version: victoria-metrics-20220121-104629-heads-public-single-node-0-gede93469e
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:13 command line flags
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "httpAuth.password"="secret"
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "httpAuth.username"="wix"
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "metricsAuthKey"="secret"
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "retentionPeriod"="4"
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "search.maxConcurrentRequests"="48"
2022-01-21T17:46:53.728Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "search.maxQueryDuration"="2m0s"
2022-01-21T17:46:53.729Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "search.maxStalenessInterval"="1m0s"
2022-01-21T17:46:53.729Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "search.maxUniqueTimeseries"="10000000"
2022-01-21T17:46:53.729Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "search.treatDotsAsIsInRegexps"="true"
2022-01-21T17:46:53.729Z  info  VictoriaMetrics/lib/logger/flag.go:20 flag "selfScrapeInterval"="10s"
2022-01-21T17:46:53.729Z  info  VictoriaMetrics/app/victoria-metrics/main.go:52 starting VictoriaMetrics at ":8428"...

2022-01-21T17:49:31.614Z  warn  VictoriaMetrics/app/vminsert/main.go:108  remoteAddr: "10.89.100.142:32468"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: cannot add 417 rows to storage in 30s, since it is overloaded with 96 concurrent writers; add more CPUs or reduce load
2022-01-21T17:49:31.706Z  warn  VictoriaMetrics/app/vminsert/main.go:108  remoteAddr: "10.89.100.142:44813"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: cannot add 424 rows to storage in 30s, since it is overloaded with 96 concurrent writers; add more CPUs or reduce load
2022-01-21T17:49:31.726Z  warn  VictoriaMetrics/app/vminsert/main.go:108  remoteAddr: "10.173.215.113:60054"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: cannot add 2683 rows to storage in 30s, since it is overloaded with 96 concurrent writers; add more CPUs or reduce load
2022-01-21T17:49:31.889Z  warn  VictoriaMetrics/app/vminsert/main.go:108  remoteAddr: "10.173.215.113:60072"; requestURI: /api/v1/write; error when processing imported data: cannot store metrics: cannot add 861 rows to storage in 30s, since it is overloaded with 96 concurrent writers; add more CPUs or reduce load`

Snapshot of metrics including the requested 3 (bottom most graphs, but theres 0 queries there. Only writes, its a test one)
[here](https://grafana.wixpress.com/dashboard/snapshot/PFwretbcS2ViPkThSgRqdUeEiPvDadBy?orgId=1)

maxConcurrentInserts and maxConcurrentInserts are at their default values, maybe i should tune them?

**Comment by valyala** [comment]
> maxConcurrentInserts and maxConcurrentInserts are at their default values, maybe i should tune them?

There is no need to tune these settings, since they aren't related to the original issue.

I was able to reproduce the issue by running VictoriaMetrics, which collects big number of metrics with frequently changhing labels from [avalanche](https://github.com/prometheus-community/avalanche). This emulates high churn rate. VictoriaMetrics stores an `metric_name{labels} -> internal_series_id` entry in the internal database (aka `indexdb`) for every new time series (a time series is uniquely identified by metric name plus a set of its labels, e.g. `foo{foo="value1"}` and `foo{label="value2"}` are two different time series, since they differ by the value of `foo` label). These entries are used for looking up for `internal_series_id` by `metric_name{labels}` for every incoming sample. This means that the number of such entries in `indexdb` equals to the **total** number of time series with at least a single sample, which were ingested into VictoriaMetrics during 2x of the configured `-retentionPeriod`. For example, if daily churn rate is 150 millions of new time series and the `-retentionPeriod` is set to 30 days, then the total number of `metric_name{labels} -> internal_series_id` entries in `indexdb` will be `150M*30*2=9 billions`. The actual total number of time series stored in VictoriaMetrics can be obtained via `http://victoriametrics:8428/api/v1/series/count` handler. Note that the handler actually scans all the registered time series, so it can take extended amounts of time to return on big databases.

Let's look at how VictoriaMetrics accepts new samples. On every new sample it consults e.g. `tsid cache`, which is stored in memory. This cache contains the same `metric_name{labels} -> internal_series_id` entries for recently ingested time series. If the entry isn't found in the cache (aka cache miss), then VictoriaMetrics falls back to reading the entry from `indexdb`. This operation may be quite slow, since the data is read from `indexdb` in blocks. Every block may contain big number of `metric_name{labels} -> internal_series_id` entries (usually in the range of 1000). Every block is stored in a compressed form on disk in order to reduce disk space usage. So VictoriaMetrics needs to read the block from disk, then unpack it and then check for the requested entry in the block. Obviously, this operation is multiple orders of magnitude slower than a simple lookup in the `tsid cache`. It needs additional disk read IO and CPU.

VictoriaMetrics has an additional in-memory cache in order to speed up the lookup in `indexdb` when the entry isn't found at `tsid cache`. This cache is named `indexdb/dataBlocks`. It contains unpacked blocks from `indexdb`. This allows avoiding additional CPU and disk read IO usage when querying for the `metric_name{labels} -> internal_series_id` entry, which wasn't found in the `tsid cache`.

Now let's return the the issue. It triggers when the following conditions are met simultaneously:
1) When `tsid cache` is empty. The cache is loaded from disk on startup if the cache was stored to disk during the previous graceful shutdown of VictoriaMetrics. The cache can become empty on startup in the following cases:
  * On unclean shutdown (for example, after out of memory error or after `kill -9`).
  * If `-memory.allowedPercent` or `-memory.allowedBytes` command-line flags were changed since the last graceful shutdown.
  * If VictoriaMetrics has been migrated to a host with another amounts of RAM.
  * If the cache directory has been manually removed. The cache is stored at `<-storageDataPath>/cache` directory.
2) When the `indexdb/dataBlocks` cache size isn't enough for caching frequently requested `indexdb` blocks. This results in low cache hit rate, so VictoriaMetrics needs to spend CPU and disk read IO for re-reading missing blocks from disk. This may be the case when `indexdb` contains big number of `metric_name{labels} -> internal_series_id` entries because of high churn rate. 

If both conditions are met, then VictoriaMetrics may accept new samples at very slow rate (aka [slow insert](https://docs.victoriametrics.com/FAQ.html#what-is-a-slow-insert) ) until it fills `tisd cache` with entries for [active time series](https://docs.victoriametrics.com/FAQ.html#what-is-an-active-time-series). The performance should return to normal after the `tsid cache` is filled with the needed data. The `tsid cache` is populated quite fast if the `indexdb/dataBlocks` cache has enough capacity for caching frequently requested `indexdb` blocks. Unfortunately this isn't the case here because of too big number of `metric_name{labels} -> internal_series_id` entries in `indexdb`.

I tried improving the situation in multiple ways:
* Optimizing the `indexdb/dataBlocks` cache, so it could hold more `indexdb` blocks in the same amounts of memory.
* Increasing the lifetime for `indexdb/dataBlocks` entries. Previously the entries were evicted after 2 minutes of inactivity. Now the lifetime has been increased to 5 minutes. This should help during cold startup with empty `tsid cache` when samples for the same time series could be ingested with higher interval due to slow inserts. If the interval exceeds 2 minutes, then the corresponding entry in the cache could be evicted before the next sample for the given time series arrives.
* Skipping caching `indexdb` blocks, which were requested only once. This should prevent from evicting requested blocks on on-off heavy queries (`indexdb` is used also for looking up the needed time series during queries).

These changes are included into `victoriametrics/victoria-metrics:heads-public-single-node-0-gd0f785def` docker image. @Alexul , it would be great if you could test this image. Note that VictoriaMetrics may need additional time for populating the `tsid cache` on first startup when `tsid cache` is empty. The next restart should take lower amounts of time.

**Comment by Alexul** [comment]
Thank you for detailed explanation!
Tried with `heads-public-single-node-0-gd0f785def`, cannot start after 20m (assuming repopulation tsid scenario)
Snapshot [here](https://grafana.wixpress.com/dashboard/snapshot/QdOLlH1CX0LQraay10gMUE3mN7NhPchF)
CPU/Disk usage is very low. Attaching 2 dumps, `start` one on the starting phase and second one from before i stopped and RBed to 1.70.0
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8021695/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8021697/mem.pprof.txt)
[cpu-start.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8021699/cpu-start.pprof.txt)
[mem-start.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8021700/mem-start.pprof.txt)

**Comment by Alexul** [comment]
<img width="1384" alt="Screen Shot 2022-02-08 at 09 49 51" src="https://user-images.githubusercontent.com/10867201/152941759-c73be3f9-5e1b-4467-86ae-5383e87e50b6.png">
Please not the difference in growth of IDS number new version vs 1.70.0
Also `indexdb/dataBlocks` is at max only 156GB, should fit in mem just fine

**Comment by valyala** [comment]
Thanks for the provided information. It looks like the `indexdb/dataBlocks` cache capacity was too small for the given workload (e.g. the cache capacity was limited to 110GB, while it needs 158GB for optimal performance according to the graph above). The cache capacity has been increased in 2455a988e48fa354b1bd7227e6499c34583a597b . Additionally, the global lock for `indexdb/dataBlocks` cache has been  split into per-CPU locks at 4507b111a9a2519f62f223184bc7e4c1d536a6b9 . This should improve CPU utilization (currently only 8 out of 96 CPUs are used during `tsid cache` population). This should reduce the time needed to populate `tsid cache`.

@Alexul , could you try VictoriaMetrics from `victoriametrics/victoria-metrics:heads-public-single-node-0-gdb8c4054e` docker image? It includes optimizations mentioned above.

**Comment by Alexul** [comment]
Yep, it worked, but took ~20 mins to start
[metrics](https://grafana.wixpress.com/dashboard/snapshot/330qi7XG8CMaT1Kdbo5HUHa7NTPEOBqi)
Seems to be hitting the mem limit on `indexdb/dataBlocks`, can we increase it?
Also why `indexdb/dataBlocks` is that big on the start and then drops significantly?
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8030844/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8030845/mem.pprof.txt)

**Comment by valyala** [comment]
> Seems to be hitting the mem limit on indexdb/dataBlocks, can we increase it?

The limit for `indexdb/dataBlocks` cache can be increased only indirectly via either `-memory.allowedPercent` or `-memory.allowedBytes` command-line flags. There are plans to provide additional command-line flags for fine-grained limits per each cache. See [this feature request](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1940) for details.

> Also why indexdb/dataBlocks is that big on the start and then drops significantly?

VictoriaMetrics needs to read many blocks from indexdb on the start. These blocks contain `metric_name{labels} -> internal_metric_id` entries. The number of such blocks may be too big if `indexdb` knows about big number of time series like in your case. After the start these blocks aren't needed by VictoriaMetrics, so they are eventually removed from `indexdb/dataBlocks` cache. These blocks aren't needed also on the next start if the `storage/tsid` cache has been correctly saved to disk during the previous graceful shutdown. More details are available [in this comment](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/2007#issuecomment-1032080840).

**Comment by valyala** [comment]
@Alexul , could you try [VictoriaMetrcs v1.73.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) and collect CPU+mem profiles during its start when it populates tsid cache? This release re-populates tsid cache after the upgrade from the previous release because its contents changes due to the fix for [this issue](https://github.com/VictoriaMetrics/VictoriaMetrics/issues/1401). The tsid cache should be persisted during the next graceful shutdown, so it should be pre-filled during the next restarts.

**Comment by Alexul** [comment]
I am currently running gdb8c4054e, will it repopulate tsid cache on upgrade to 1.73.0? Should i change `-memory.allowedPercent` to force it?

**Comment by valyala** [comment]
> I am currently running gdb8c4054e, will it repopulate tsid cache on upgrade to 1.73.0?

Yes

> Should i change -memory.allowedPercent to force it?

No

**Comment by Alexul** [comment]
Seems like new versions set even less memory towards `indexdb/dataBlocks`...
Even increasing -memory.allowedPercent from default to 80 doesnt help.
Meanwhile theres a lot of cache mem just sitting there not used at all
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8080596/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8080597/mem.pprof.txt)

<img width="690" alt="Screen Shot 2022-02-16 at 16 22 37" src="https://user-images.githubusercontent.com/10867201/154284445-60eb5438-a499-440f-8dd2-81c7f87afad0.png">

**Comment by valyala** [comment]
> Seems like new versions set even less memory towards `indexdb/dataBlocks`.

This is made on purpose, since it has been appeared that the increased default limits for `indexdb/dataBlocks` and `indexdb/indexBlocks` caches led to increased memory usage in many productions setups for VictoriaMetrics comparing to pre-v1.73.0 releases. So the default limit has been reduced further. But now it can be overridden via `-storage.cacheSizeIndexDBDataBlocks` and `-storage.cacheSizeIndexDBIndexBlocks` command-line flags - read below.

@Alexul , could you try running single-node VictoriaMetrics from Docker tag `heads-public-single-node-0-gf72b35665` ? It includes the following improvements on top of v1.73.0:

* Better cache eviction policy. Now it removes least recently used items when the cache reaches its max size limit. Previously it could remove arbitrary items. This improvement should reduce cache miss ratio, which can be checked with the following query: `rate(vm_cache_misses_total{type=~".+Blocks"}) / rate(vm_cache_requests_total)` . It also should reduce the average cache size utilization in the long run. It can be checked with the following query: `vm_cache_size_bytes{type=~".+Blocks"} / vm_cache_size_max_bytes` .
* Added an ability to override cache size limits for the following caches:
  * `storage/tsid` - via `-storage.cacheSizeStorageTSID` command-line flag.
  * `indexdb/dataBlocks` - via `-storage.cacheSizeIndexDBDataBlocks` command-line flag.
  * `indexdb/indexBlocks` - via `-storage.cacheSizeIndexDBIndexBlocks` command-line flag.
* Reduced memory usage with default cache size settings.

**Comment by Alexul** [comment]
[Snapshot with heads-public-single-node-0-gf72b35665](https://grafana.wixpress.com/dashboard/snapshot/VT85vwrsjx5XSF1x38aNZszO1ZIZACXv?orgId=1&refresh=1m)
It started after 15min, seems like `-storage.cacheSizeIndexDBDataBlocks 180GB` was ignored or did i get syntax wrong?

**Comment by Alexul** [comment]
works in v1.73.1
but for whatever reason giving more cache to `indexdb/dataBlocks` increases overall Victoria mem usage considerable. Till it OOMs (nothing in the logs)
[graphs of Victoria](https://grafana.wixpress.com/dashboard/snapshot/61fGUbQ3QEzZlujkT1McegDsYenq3MRh?orgId=1)
graphs of machine it runs on:
<img width="348" alt="Screen Shot 2022-02-23 at 10 43 43" src="https://user-images.githubusercontent.com/10867201/155286062-bc58793b-f9b9-4888-9cee-31fdedfb5a0e.png">
[cpu.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8122908/cpu.pprof.txt)
[mem.pprof.txt](https://github.com/VictoriaMetrics/VictoriaMetrics/files/8122909/mem.pprof.txt)

**Comment by valyala** [comment]
Just discovered a memory leak at `indexdb/dataBlocks`, `indexdb/indexBlocks` and `storage/indexBlocks` caches. This memory leak has been introduced in v1.73.0. The memory leak should be fixed in Docker image tag `heads-public-single-node-0-ge3a10b327`. @Alexul , could you try this Docker image and verify whether it helps reducing memory usage in your case?

**Comment by Alexul** [comment]
Ohh, yes
<img width="666" alt="Screen Shot 2022-03-18 at 19 23 12" src="https://user-images.githubusercontent.com/10867201/159052542-755de0fb-996c-4d46-85d2-04cfd85f1e88.png">

**Comment by valyala** [comment]
@Alexul , thanks for the confirmation! The bugfix has been included in [VictoriaMetrics v1.75.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Then closing the issue as fixed.
