### ISSUE TITLE
retentionPeriod odd behavior. Data has been cleared on the first day of the month.

### ISSUE THREAD

**Issue by velychkovsky** [VictoriaMetrics/VictoriaMetrics#248]
**Describe the bug**
I have default setup of VictoriaMetrics with retentionPeriod=1m, and my data were deleted on 1'st of December.

**To Reproduce**
Run Victoriametrics 25 of November and then check your data on 1'st of december. They will be cleaned at midnight. 

**Expected behavior**
I'm expecting that Storage engine should remember retentionPeriod and check if my data has overtime this period, and delete it.  Because in the worst case I can lose data for 1 month. 

**Version**

```
$ docker exec victoriametrics ./victoria-metrics-prod --version
victoria-metrics-20191126-001035-tags-v1.30.0-0-g205233d9
```

**Container logs**
```
2019-11-30T23:59:59.953+0000    info    VictoriaMetrics@/lib/mergeset/table.go:190      table "/victoria-metrics-data/indexdb/15DB586BC57EF882" has been opened in 9.867058ms; partsCount: 0; blocksCount: 0, itemsCount: 0; sizeBytes: 0
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:206      waiting for raw items flusher to stop on "/victoria-metrics-data/indexdb/15DB57652FD931A3"...
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:209      raw items flusher stopped in 587ns on "/victoria-metrics-data/indexdb/15DB57652FD931A3"
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:211      waiting for converters to stop on "/victoria-metrics-data/indexdb/15DB57652FD931A3"...
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:214      converters stopped in 40.886µs on "/victoria-metrics-data/indexdb/15DB57652FD931A3"
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:216      waiting for part mergers to stop on "/victoria-metrics-data/indexdb/15DB57652FD931A3"...
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:219      part mergers stopped in 1.058µs on "/victoria-metrics-data/indexdb/15DB57652FD931A3"
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:221      flushing inmemory parts to files on "/victoria-metrics-data/indexdb/15DB57652FD931A3"...
2019-11-30T23:59:59.955+0000    info    VictoriaMetrics@/lib/mergeset/table.go:245      0 inmemory parts have been flushed to files in 3.958µs on "/victoria-metrics-data/indexdb/15DB57652FD931A3"
2019-11-30T23:59:59.956+0000    info    VictoriaMetrics@/lib/storage/index_db.go:352    dropping indexDB "/victoria-metrics-data/indexdb/15DB57652FD931A3"
2019-11-30T23:59:59.960+0000    info    VictoriaMetrics@/lib/storage/index_db.go:354    indexDB "/victoria-metrics-data/indexdb/15DB57652FD931A3" has been dropped
2019-12-01T00:00:00.000+0000    info    VictoriaMetrics@/lib/mergeset/table.go:156      opening table "/victoria-metrics-data/indexdb/15DB586BC57EF883"...
2019-12-01T00:00:00.006+0000    info    VictoriaMetrics@/lib/mergeset/table.go:190      table "/victoria-metrics-data/indexdb/15DB586BC57EF883" has been opened in 6.03645ms; partsCount: 0; blocksCount: 0, itemsCount: 0; sizeBytes: 0
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:206      waiting for raw items flusher to stop on "/victoria-metrics-data/indexdb/15DB57652FD931A4"...
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:209      raw items flusher stopped in 824ns on "/victoria-metrics-data/indexdb/15DB57652FD931A4"
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:211      waiting for converters to stop on "/victoria-metrics-data/indexdb/15DB57652FD931A4"...
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:214      converters stopped in 387ns on "/victoria-metrics-data/indexdb/15DB57652FD931A4"
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:216      waiting for part mergers to stop on "/victoria-metrics-data/indexdb/15DB57652FD931A4"...
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:219      part mergers stopped in 675ns on "/victoria-metrics-data/indexdb/15DB57652FD931A4"
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:221      flushing inmemory parts to files on "/victoria-metrics-data/indexdb/15DB57652FD931A4"...
2019-12-01T00:00:00.008+0000    info    VictoriaMetrics@/lib/mergeset/table.go:245      0 inmemory parts have been flushed to files in 6.228µs on "/victoria-metrics-data/indexdb/15DB57652FD931A4"
2019-12-01T00:00:00.010+0000    info    VictoriaMetrics@/lib/storage/index_db.go:352    dropping indexDB "/victoria-metrics-data/indexdb/15DB57652FD931A4"
2019-12-01T00:00:00.318+0000    info    VictoriaMetrics@/lib/storage/index_db.go:354    indexDB "/victoria-metrics-data/indexdb/15DB57652FD931A4" has been dropped
2019-12-01T00:00:00.562+0000    info    VictoriaMetrics@/lib/storage/partition.go:197   creating a partition "2019_12" with smallPartsPath="/victoria-metrics-data/data/small/2019_12", bigPartsPath="/victoria-metrics-data/data/big/2019_12"
2019-12-01T00:00:00.577+0000    info    VictoriaMetrics@/lib/storage/partition.go:212   partition "2019_12" has been created
```

**Comment by valyala** [comment]
Confirmed the bug. It could trigger due to time drift on the computer. According to logs, it performed the first indexdb rotation 50ms before 2019-12-01 and then performed yet another rotation at the beginning of 2019-12-01. The second one rotation shouldn't trigger if there was no time drift. It removed inverted index data for November. This made all the data from November unavailable.

The issue will be fixed in the next VictoriaMetrics release.

**Comment by valyala** [comment]
The issue should be fixed in the commit https://github.com/VictoriaMetrics/VictoriaMetrics/commit/62a915f2b2892632b090f1e876fc32c303b9e4fa

**Comment by velychkovsky** [comment]
Thank you for hot fix! 
@valyala how often do you update your docker images on docker hub, and when this fix will be deployed to docker image?

**Comment by valyala** [comment]
The fix is already available starting from [v1.30.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). The corresponding Docker images are already pushed to https://hub.docker.com/u/victoriametrics .

Closing the issue as fixed.

**Comment by valyala** [comment]
@velychkovsky , I'd recommend upgrading to [v1.30.3](https://github.com/VictoriaMetrics/VictoriaMetrics/releases), since it fixes a few issues found in v1.30.2.

**Comment by heliodor** [comment]
With the version that fixes this bug, does the incorrectly dropped data become visible again by simply upgrading? If not, is there a way to have the dropped data appear in queries again? @valyala, I'm referring to the oldest one month of data that you mentioned is still present but invisible to incoming queries before it gets deleted from disk a mont later.

**Comment by valyala** [comment]
> With the version that fixes this bug, does the incorrectly dropped data become visible again by simply upgrading? If not, is there a way to have the dropped data appear in queries again?

While the data is still there, all the inverted index entries for locating this data are lost, so it is impossible to map the data to metric names and labels :(

**Comment by valyala** [comment]
The data could be restored from [backups](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmbackup/README.md) if they exist.
