### ISSUE TITLE
vmagent: the load to consul sd increases every time on reloads with changed relabeling configuration

### ISSUE THREAD

**Issue by wf1nder** [VictoriaMetrics/VictoriaMetrics#3468]
We using vmagent with consul service discovery, and we have some set of relabeling configuration.
Recently we noticed that "health" queries rate to consul (consul agent) is increasing every time we made changes to relabeling config, at least to `metric_relabel_configs` sections, and apply it by its "reload" command (via `/-/reload` handler in our case).
And it doesn't matter what kind of changes we made: change, remove or add relabeling sections. Load to consul increasing every time.

Below is an example part of a set of rules that we operate:
```
      - source_labels: ['_noenrich2']
        regex: '(1)'
        target_label: '_allocation_id'
        replacement: ''
      - source_labels: ['_noenrich2']
        regex: '(1)'
        target_label: '_allocation_index'
        replacement: ''
      - source_labels: ['_noenrich2']
        regex: '(1)'
        target_label: '_version'
        replacement: ''
      - source_labels: ['_noenrich2']
        regex: '(1)'
        target_label: 'container_ip'
        replacement: ''
      - source_labels: ['_noenrich2']
        regex: '(1)'
        target_label: 'docker_host'
        replacement: ''
      - source_labels: ['_noenrich2']
        regex: '(1)'
        target_label: 'instance'
        replacement: ''
      - regex: '_noenrich2'
        action: labeldrop
```

At 23:13 we renamed a label `_noenrich2` to `_noenrich3`, and then at 23:38 we deleted the set of rules given above. At 00:00 we restarted vmagent, and query rate returned to usual.

![Screenshot 2022-12-11 at 00 17 19](https://user-images.githubusercontent.com/4486762/206869607-fbf0d09b-b057-45d7-b641-c2f937ced21e.png)

Consul server don't like this type of load, this causes him to grow up some internal metrics like goroutines count, increasing resources consumption.

![Screenshot 2022-12-11 at 00 17 29](https://user-images.githubusercontent.com/4486762/206869922-f785befa-5d9e-4aec-8bd5-dbc26b28ad4f.png)

Tested on versions: 1.79.5, 1.80.0, 1.84.0, the behavior is the same on all of them.

I assume that there is some kind of leak in vmagent, maybe some workers don't stops on reloads, or something like that.

**Comment by valyala** [comment]
@zekker6 , could you try reproducing and fixing this issue?

**Comment by valyala** [comment]
See the related comment https://github.com/VictoriaMetrics/VictoriaMetrics/issues/3385#issuecomment-1345486644

**Comment by zekker6** [comment]
@valyala Tested both nomad & consul discovery, both work well apart from one misusage of timeout. Fixed it here: #3609

**Comment by valyala** [comment]
vmagent and single-node VictoriaMetrics should properly free up resources occupied by the previous `consul_sd_configs` configs on config update starting from [the release v1.86.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@wf1nder , feel free re-opening the issue if Consul service discovery doesn't work as expected in `vmagent v1.86.0`.

**Comment by wf1nder** [comment]
Unfortunately, the situation didn't improved much in our case. On vmagent v1.86.0 before and after reload at 21:10:

![Screenshot 2023-01-11 at 21 38 45](https://user-images.githubusercontent.com/4486762/211849507-bacbd4ad-8093-4f49-a3fd-877651b658ec.png)
![Screenshot 2023-01-11 at 21 38 57](https://user-images.githubusercontent.com/4486762/211849531-d6f722c9-d3c6-4071-b5aa-df543e75e3c3.png)

I took heap dumps before and after reload, and sent it to info@victoriametrics.com

**Comment by zekker6** [comment]
Hi @wf1nder 
Could you share graphs for `vm_promscrape_discovery_consul_service_watchers`, `vm_promscrape_discovery_consul_service_watchers_created_total` and `vm_promscrape_discovery_consul_service_watchers_stopped_total` metrics for the period when consul reload is triggered?
This should show if there are workers left in the background which were not stopped properly.

**Comment by wf1nder** [comment]
@zekker6 reload at 12:36:

![Screenshot 2023-01-14 at 12 48 44](https://user-images.githubusercontent.com/4486762/212459844-6d1ee26b-7deb-4f38-a9a0-fb2885b7b79a.png)

**Comment by zekker6** [comment]
@wf1nder Thank you for sharing graph!

Fix for this issue is available at https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3658 and will be included in the next release. 

In case it is possible to verify that it works with your workload there is a docker image reference built from this PR: `victoriametrics/vmagent:heads-fix-vmagent-hashicorp-discovery-cancel-service-watchers-0-g4ee38e38e`.
Also, if you need another packaging format you can build from source by using [this doc](https://github.com/VictoriaMetrics/VictoriaMetrics#how-to-build-from-sources)

**Comment by wf1nder** [comment]
@zekker6 Unfortunately the problem still persists:

![Screenshot 2023-01-17 at 07 11 58](https://user-images.githubusercontent.com/4486762/212788429-ec6bc5dc-726a-49db-88e1-cac88c44abbb.png)

Deployed version from PR above at 06:50, and apply changes with reload at 06:57.
I double-checked that version is `vmagent-20230117-003945-heads-fix-vmagent-hashicorp-discovery-cancel-service-watchers-0-g4ee38e38e`.

**Comment by zekker6** [comment]
@wf1nder Thank you for checking!
I think it should be now fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3658/commits/2c08c04817f1f04a184868b3b0a5047eb223842a
Here is a new image built from the latest commit of same PR: `victoriametrics/vmagent:heads-fix-vmagent-hashicorp-discovery-cancel-service-watchers-0-g2c08c0481`
Would really appreciate if you could check new image as well.

**Comment by valyala** [comment]
@wf1nder , the commit 322d96bfe5ecc3dbb1a7149f8741c3b869486ce1 contains all the fixes mentioned above. Could you try the Docker image `docker.io/victoriametrics/vmagent:heads-public-single-node-0-g322d96bfe` built from this commit?

**Comment by valyala** [comment]
@wf1nder , could you try [vmagent v1.86.2](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)? It includes all the fixes mentioned above.

**Comment by wf1nder** [comment]
@valyala @zekker6 Sorry for late answer. Checked on version v1.86.2, unfortunately it's still not good. The load on consul has also grown a bit. Performed reload at 7:46:

![Screenshot 2023-01-19 at 07 56 30](https://user-images.githubusercontent.com/4486762/213337525-d5be82ef-1907-41d0-9b88-cfd24c163abb.png)

**Comment by zekker6** [comment]
@wf1nder From the graph above I can see that vmagent created more watchers than stopped which resulted in higher amount of total watchers running. This should lead to increased load to consul for targets initial discovery but than it should go back to normal. According to this graph, it seems like vmagent discvovered twice more targets than it was before reload. Is that expected?

Current config update for vmagent logic will trigger restarting job in case any of it fields was modified(`metric_relabel_configs` in this case). When job is restarted vmagent uses the same flow as on start: discover existing services and subscribe to updates.
The only way we can optimize vmagent that I can see is to update existing job in-place and apply new relabeling rules without stopping scrape job. That would make reloads lighter for the jobs which only change relabel configs as it won't re-run discovery itself.
@valyala Please, correct me if I'm missing something here. If that makes sense, I think we can implement this.

**Comment by wf1nder** [comment]
> it seems like vmagent discvovered twice more targets than it was before reload. Is that expected?
No, this is not expected. The number of targets has not changed, only the relabeling rules have changed, like described in topic. And it doesn't matter if we added or removed the specified set of rules, the result is the same. @zekker6

**Comment by zekker6** [comment]
@wf1nder Could you check log messages during reload for a message similar to this one?
```
info    lib/promscrape/scraper.go:421   consul_sd_configs: added targets: 1, removed targets: 1; total targets: 19989
```
I'd like to make sure metrics are reporting correct values here.
Did some testing with consul with large amount of targets, but wasn't able to reproduce discovering twice more targets that it was before reload so far.

**Comment by wf1nder** [comment]
@zekker6 Here are the messages from log at the time of reload (at 11:22), before which I added rules like in topic into `metric_relabel_configs` section:
```
 2023-02-03T05:21:41.282Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 0, removed targets: 1; total targets: 1404
 2023-02-03T05:21:41.744Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 1, removed targets: 0; total targets: 1405
 2023-02-03T05:22:36.183Z info VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:170 SIGHUP received; reloading relabel configs pointed by -remoteWrite.relabelConfig and -remoteWrite.urlRelabelConfig
 2023-02-03T05:22:36.183Z info VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:182 Successfully reloaded relabel configs
 2023-02-03T05:22:36.183Z info VictoriaMetrics/lib/promscrape/scraper.go:150 SIGHUP received; reloading Prometheus configs from "/etc/scrape.yml"
 2023-02-03T05:22:36.193Z info VictoriaMetrics/lib/promscrape/config.go:131 restarting service discovery routines...
 2023-02-03T05:22:36.193Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.354Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.161 seconds
 2023-02-03T05:22:36.355Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.485Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.130 seconds
 2023-02-03T05:22:36.485Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.485Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:22:36.486Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.634Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.148 seconds
 2023-02-03T05:22:36.634Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.769Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.135 seconds
 2023-02-03T05:22:36.770Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.770Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:22:36.770Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.770Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:22:36.770Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.771Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:22:36.771Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:22:36.771Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:22:36.771Z info VictoriaMetrics/lib/promscrape/config.go:174 restarted service discovery routines in 0.578 seconds, stopped=0, started=0, restarted=3
 2023-02-03T05:22:36.773Z info VictoriaMetrics/lib/promscrape/scraper.go:192 found changes in "/etc/scrape.yml"; applying these changes
 2023-02-03T05:23:04.678Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 0, removed targets: 1; total targets: 1404
 2023-02-03T05:23:04.679Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:05.502Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:06.805Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:06.886Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:08.324Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:09.622Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:09.983Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:10.111Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:10.244Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:23:18.697Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 1195, removed targets: 1194; total targets: 1405
 2023-02-03T05:24:20.900Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 1, removed targets: 1; total targets: 1405
```

And then I removed this rules from relabel config (at 11:30):
```
 2023-02-03T05:28:37.056Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 0, removed targets: 1; total targets: 1403
 2023-02-03T05:30:19.295Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 2, removed targets: 0; total targets: 1405
 2023-02-03T05:30:34.488Z info VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:170 SIGHUP received; reloading relabel configs pointed by -remoteWrite.relabelConfig and -remoteWrite.urlRelabelConfig
 2023-02-03T05:30:34.488Z info VictoriaMetrics/lib/promscrape/scraper.go:150 SIGHUP received; reloading Prometheus configs from "/etc/scrape.yml"
 2023-02-03T05:30:34.488Z info VictoriaMetrics/app/vmagent/remotewrite/remotewrite.go:182 Successfully reloaded relabel configs
 2023-02-03T05:30:34.499Z info VictoriaMetrics/lib/promscrape/config.go:131 restarting service discovery routines...
 2023-02-03T05:30:34.499Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:34.680Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.181 seconds
 2023-02-03T05:30:34.680Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:34.816Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.136 seconds
 2023-02-03T05:30:34.817Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:34.817Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:30:34.817Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:34.951Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.133 seconds
 2023-02-03T05:30:34.951Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:35.085Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.134 seconds
 2023-02-03T05:30:35.085Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:35.085Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:30:35.085Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:35.086Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:30:35.086Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:35.086Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:30:35.086Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:184 stopping Consul service watchers for "http://localhost:9500"
 2023-02-03T05:30:35.086Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:199 stopped Consul service watcher for "http://localhost:9500" in 0.000 seconds
 2023-02-03T05:30:35.086Z info VictoriaMetrics/lib/promscrape/config.go:174 restarted service discovery routines in 0.588 seconds, stopped=0, started=0, restarted=3
 2023-02-03T05:30:35.088Z info VictoriaMetrics/lib/promscrape/scraper.go:192 found changes in "/etc/scrape.yml"; applying these changes
 2023-02-03T05:30:35.088Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:36.064Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:37.124Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:37.197Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:38.517Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:39.934Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:40.037Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:40.130Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:30:40.268Z info VictoriaMetrics/lib/promscrape/discovery/consul/watch.go:169 started Consul service watcher for "http://localhost:9500"
 2023-02-03T05:34:07.527Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 1195, removed targets: 1195; total targets: 1405
 2023-02-03T05:34:07.974Z info VictoriaMetrics/lib/promscrape/scraper.go:421 consul_sd_configs: added targets: 2, removed targets: 3; total targets: 1404
```

![Screenshot 2023-02-03 at 11 36 52](https://user-images.githubusercontent.com/4486762/216521123-ce90cc75-a068-4f11-a0b2-4368abf8bd36.png)

And now I realized that it looks like the problem is no longer reproducing. The load on the consul server did not increase this time either, on both adding and removing relabel rules.
The vmagent configuration and the scrape config have not changed, but a couple of days ago we updated the version of the consul server, from v1.9.5 to v1.14.3. Maybe the problem was somehow related to the version of the consul server.

I'm sorry if I wasted your time.

**Comment by zekker6** [comment]
@wf1nder Glad to hear that :)
No worries, we prefer to make sure there are no issues on our side.
I'll close this issue for now then, feel free to reopen if it will become reproducible.
