### ISSUE TITLE
vmstorage configuration to minimize storage spikes

### ISSUE THREAD

**Issue by akamensky** [VictoriaMetrics/VictoriaMetrics#3743]
We are moving away from Prometheus to clustered VM, which appears to work better in terms of horizontal scaling, performance and redundancy.

However, I noticed `vmstorage` regularly will create temporary data that consumes large amount of storage. We are still ingesting data (the first data didn't reach retention limit yet). But we already see those periodic spikes consuming double the storage for some time (graph shows single node, but it happens across all of them) :

![image](https://user-images.githubusercontent.com/985805/216186080-33f258fa-bda8-4263-a9cd-4096f0a478f9.png)

Is there anything we are missing configuration wise on vmstorage that would avoid those spikes or make them much smaller?

The concern here is that we are on physical server setup and the storage is obviously limited there, the data retention is setup based on projection of vmstorage using ~80% of total disk space, but if it will be spiking up to double, we will run out of disk space (and not clear what happens then? crash?)

The setup is: vmagent (w/ prometheus scraping configs) -> nginx -> 3x vminsert (configured to replicate to 2 nodes) -> 3x vmstorage <- 3x vmselect <- nginx <- Grafana. All this running on Docker using official images from Docker Hub.

vmstorage configuration:

```yaml
  vmstorage:
    image: "victoriametrics/vmstorage:v1.86.2-cluster"
    network_mode: "host"
    volumes:
      - "/data/vmstorage:/storage"
    command:
      - "--storageDataPath=/storage"
      - "--retentionPeriod=XXd"
      - "--dedup.minScrapeInterval=15s"
      - "--memory.allowedPercent=10"
    restart: "always"
```

**Comment by zekker6** [comment]
@akamensky This seems to be related to a bug which was fixed in the [v1.87.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.87.0) release. It was causing background merges to be run too often for data stored in previous month(and as far as  I can see from the graph in your case most of the data is related to the previous month):

> BUGFIX: fix a bug, which could lead to increased CPU usage and disk IO usage when adding data to previous months and when the [deduplication](https://docs.victoriametrics.com/#deduplication) or [downsampling](https://docs.victoriametrics.com/#downsampling) is enabled. See https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3737.

During background merge parts are copied to a new folder under `tmp`, merged and then merged parts atomically replace original ones. This process takes as much space as original part did, but this process will not be started if there is not enough disk space to create a copy of part.

Could you check if updating to v1.87.0 helps to keep disk space usage more stable?

**Comment by akamensky** [comment]
@zekker6 Thanks I will update it ASAP.

**Comment by akamensky** [comment]
@zekker6 in general other than that big spike, how to minimize those smaller ones? It would be nice to have more predictable storage usage, and the smaller spikes (that happen multiple times every day) can also use quite a bit of storage. Or is it the same bug just different presentation?

**Comment by akamensky** [comment]
@zekker6 I've upgraded vmstorage/vminsert/vmselect to 1.87.0, after upgrade I still see rather substantial spike in disk usage (correlates with vmstorage log entries of merging data).

![image](https://user-images.githubusercontent.com/985805/216484432-51bd1e05-4c72-461b-9778-216b849ba619.png)

I guess this may be a residual of the older data?

**Comment by zekker6** [comment]
> I guess this may be a residual of the older data?

That's right, this should be merges of data for previous month.

> Is there any way to limit the size of what should be considered for merging?

No, there is no option to control this at the moment.
It is recommended to not run VictoriaMetrics components alongside other workloads on the same host for best performance. This is because with default configurations VictoriaMetrics will consume all available resources, including disk space that might be required for internal processes.
If there will be not enough space to perform such merge vmstorage will not start merge and will write a log message about that.

Typically, merge process does not have such big effect on disk usage as in case of retention configuration larger than 1 month it will become smaller fraction of data than overall data size.

In case you need to limit disk usage because single host has some other colocated workloads and such spikes can lead to misfunction of other workloads it is better to move data folder for vmstorage at it's own volume. This will help to limit vmstorage to using single volume, and it won't affect other workloads.

**Comment by akamensky** [comment]
@zekker6 Thanks for your comment.

> No, there is no option to control this at the moment.

I think some controls/tunables for that would be great addition to this project.

> It is recommended to not run VictoriaMetrics components alongside other workloads on the same host for best performance.

It's not about running multiple services on vmstorage hosts, but about utilizing storage more efficiently and being able to predict storage utilization based on configuration. We would of course would like to adjust our retention period to be able to keep metric for longer, with these spikes we would like to be able to predict that the system won't start failing (as documentation reads that it will stop accepting writes when it reaches a threshold). As example, when we will reach 90% disk space utilization on 1TB volume, that would leave 100GB for any potential "spikes". Without any tunables (and according to documentation) I would expect the node to stop receiving writes (which IMO worst failure mode as newest metric more valuable than older ones). Hence I raised this ticket.

Now, reading your comment I am not sure whether that means the merge will not happen, but node will keep accepting writes (assuming the retention period configured correctly), or that the merge won't happen and node also won't accept any new writes?

I personally would like to be able to set an upper bound for dataset size, where if the the system detects reaching this threshold it would drop oldest metrics to accommodate for new (instead of rejecting writes), but that may be not suitable for all cases.

**Comment by zekker6** [comment]
> Now, reading your comment I am not sure whether that means the merge will not happen, but node will keep accepting writes (assuming the retention period configured correctly), or that the merge won't happen and node also won't accept any new writes?

Taking the example of 1TB volume and 90% disk space utilization: if merge will require more than 100GB - it won't be started and storage will continue receiving new metrics.

It's important to mention that such spikes in disk usage are caused by a corner case because of data set being very specific. As far as I can see from the graph, most of the data was ingested during the last month(01/24 - 02/01) and then some data during current month(01/02 - 02/02). VictoriaMetrics storage layer stores data in partitions of specific size grouped by months.
So in this case most of the data will land into `01_2023` and the rest in `02_2023`. Later on, when merge starts it will copy the biggest art of the dataset(previous month) into new location and perform merge.

Over time, during ingestion data will become more balanced both in terms of number of partitions and their grouping by months, so merges will be much less noticable. Here is an example from one of our internal monitoring clusters:
![1675427176](https://user-images.githubusercontent.com/1367798/216605270-dfa010db-5bba-4426-a768-629049d55c1b.png)


> I personally would like to be able to set an upper bound for dataset size, where if the the system detects reaching this threshold it would drop oldest metrics to accommodate for new (instead of rejecting writes), but that may be not suitable for all cases.

There is a way to implement similar behavior, but for the case when data ingestion by cluster will be stopped due to some reason. You can think of it as a safety mechanism just to have some buffer time to fix cluster. 
[vmagent](https://docs.victoriametrics.com/vmagent.html) can also receive data by remote-write and be a proxy between client and vminsert nodes. It supports keeping ingested metrics in queue stored on local disk in case metrics cannot be sent to primary remote write target. It is possible to limit the size of this queue and when this size will be reached it will start dropping older samples in favor of new ones.

I understand that your preferred solution would be to have similar option on storage level, but, just as you mentioned, it won't be suitable for all cases.

**Comment by valyala** [comment]
The following docs may be useful in order to understand how VictoriaMetrics storage works - https://docs.victoriametrics.com/#storage

**Comment by akamensky** [comment]
@zekker6 thanks for detailed explanation. That is much clearer now.
