### ISSUE TITLE
Consul sds multi tags  relabel  with regex not works

### ISSUE THREAD

**Issue by rongfengliang** [VictoriaMetrics/VictoriaMetrics#569]
**Describe the bug**
consul sds    multi tags  relabel  with regex not works

**To Reproduce**
demo:
https://github.com/rongfengliang/VictoriaMetrics-consul-sdc
consul service:
curl -X PUT -d '{"id": "prometheus-app","name": "prometheus-app","address": "prometheus","port": 9090,"tags": ["appname:demo","appversion:v1"],"checks": [{"http": "http://prometheus:9090/metrics", "interval": "5s"}]}'  http://127.0.0.1:8500/v1/agent/service/register

**Screenshots**

![WX20200618-213538](https://user-images.githubusercontent.com/2312287/85027684-c2dd5d80-b1ac-11ea-9902-a8696144c93b.jpg)
![WX20200618-213811](https://user-images.githubusercontent.com/2312287/85027699-c8d33e80-b1ac-11ea-931d-fb103cbc70d1.jpg)

**Version**

```
docker run victoriametrics/vmagent  --version 
vmagent-20200601-102939-tags-v1.36.3-cluster-0-g37aa4fe28
```

**Comment by valyala** [comment]
@rongfengliang , thanks for the details bug report! The issue must be fixed in the commit 5820c0ffb77b9415383e8fc1ed7f9ee3bf3222d5 . Could you build `vmagent` from this commit according to [these docs](https://github.com/VictoriaMetrics/VictoriaMetrics/blob/master/app/vmagent/README.md#how-to-build-from-sources) and verify whether the issue is fixed there?

**Comment by valyala** [comment]
`vmagent` and single-node VictoriaMetrics supports regex capture groups in `target_label` starting from [v1.37.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases).

**Comment by rongfengliang** [comment]
@valyala  thanks, it works

**Comment by rparvizian-rbx** [comment]
Was this fixed for vmagent too? I'm using version 1.44.0 with a similar prometheus.yml file but it's still not outputting anything. The same configuration works with prometheus.
