### ISSUE TITLE
Different values of  histogram_quantile

### ISSUE THREAD

**Issue by MCPDanilovich** [VictoriaMetrics/VictoriaMetrics#678]
We use victoria metrics cluster installation - 2 node per every node type (vminsert, vmselect, vmstorage). Select and Insert nodes published using HAproxy. I met strange situation. Victoria the main datasource for grafana. All prom node send metrics to Victoria. I get different graphs in grafana for metric every query request:
`histogram_quantile(1, sum(rate(metric_name{app="app", kubernetes_cluster="prod-cluster"}[3m])) by (le))`
![image](https://user-images.githubusercontent.com/25364749/89589066-9c9f7a00-d84d-11ea-9064-22d8d037d7ec.png)
Next request:
![image](https://user-images.githubusercontent.com/25364749/89589125-af19b380-d84d-11ea-9ca8-2e6c04025553.png)
When i send request to prometheus directly i get the same graph every request:
![image](https://user-images.githubusercontent.com/25364749/89589205-dcfef800-d84d-11ea-8797-95c82d28fb3e.png)
Looks like it depends on vmselect node, where this request was sent. When i send request to only one node i get the same graph. 
Is it abnormal situation or i use histogram_quantile() incorrectly? 

`/usr/local/bin/victoriametrics/vminsert-prod --version vminsert-20200724-184301-tags-v1.39.0-cluster-0-gcc735da81`
All other components have the same version

**Comment by valyala** [comment]
Make sure all the `vmselect` nodes in the cluster are identically configured, i.e. they must have the same set of command-line flags. Probably, certain `vmselect` nodes don't see all the `vmstorage` nodes. This could give different query results depending on the `vmselect` node used in the query. Also make sure that historical data isn't ingested for these metrics during querying. If this is the case, then response cache must be either disabled or reset on `vmselect` nodes in order to get correct results. See [these docs](https://victoriametrics.github.io/#backfilling) for details.

**Comment by tarvip** [comment]
@MCPDanilovich what was the solution in your case? I have similar issue, every refresh returns different result, but also values are different, like in your graphs.

What I have found is that when I use a bit smaller value than `1` as scalar e.g `0.999999` then it produces same results each time and graphs matches promtheus graph.

**Comment by MCPDanilovich** [comment]
We use 0.9 percentile.

**Comment by tarvip** [comment]
@valyala any idea why using `1` is causing weird issues? In my case `vmselect` nodes are identical, I am using official victoria-metrics helm chart.

**Comment by valyala** [comment]
@f41gh7 , could you look into this issue?

**Comment by valyala** [comment]
@tarvip , which version of VictoriaMetrics do you use? Could you verify whether the issue is reproduced in the [latest available release](https://github.com/VictoriaMetrics/VictoriaMetrics/releases)?

**Comment by tarvip** [comment]
@valyala I was using 1.55.0, but now I upgraded to 1.55.1 and the issue is still there.

**Comment by f41gh7** [comment]
> @valyala any idea why using `1` is causing weird issues? In my case `vmselect` nodes are identical, I am using official victoria-metrics helm chart.
 
 I wasn't able to reproduce it at playground http://play-grafana.victoriametrics.com:3000/ and locally. 

 Can you give me query example? And may i ask you for result of two query executions, want to check how it differs. 

 Also, resetting vmselects cache, may help as well.

**Comment by tarvip** [comment]
I tried with `search.disableCache` in vmselect, it didn't help.

Query is following:
```
histogram_quantile(1, sum(rate(aggregate_persist_time_bucket{kubernetes_namespace=~"prod", app="foo-service", appComponent=~"foo"}[5m])) by (aggregate_name, le))&start=1615977030&end=1615980630&step=30
```
Unfortunately it is a query against our own custom metric.


Queries and results can be seen in attached [queries.zip](https://github.com/VictoriaMetrics/VictoriaMetrics/files/6156122/queries.zip), added also prometheus results.

**Comment by acukan** [comment]
Hi is there any update about this issue?

**Comment by hagen1778** [comment]
Hi @acukan! Do you observe the same issue with VM cluster? Does it happen to other queries?
Also, in the current master branch we have commits slightly changing the `quantile`-like funcs behaviour - see https://github.com/VictoriaMetrics/VictoriaMetrics/pull/1646. Would be cool if you can check if this changes the situation. If you want to try and test it, you only need to build and update `vmselect` component.

**Comment by valyala** [comment]
@acukan , could you try the following steps in order to rule out possible issues with the cluster itself?

0) Upgrading cluster components of VictoriaMetrics to the latest available release ([v1.72.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) now). Probably the issue has been already resolved there.

1) Performing the query with the disabled query cache. This can be done by passing `nocache=1` query arg to `http://vmselect:8481/select/<accountID>/prometheus/api/v1/query_range` endpoint according to [url format](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#url-format). For example, the following command performs `histogram_quantile(1, sum(rate(aggregate_persist_time_bucket{kubernetes_namespace=~"prod", app="foo-service", appComponent=~"foo"}[5m])) by (aggregate_name, le))` on the time range `[1615977030...1615980630]` with `step=30s` for accountID=0 with disabled response cache:

```
curl http://vmselect:8481/select/0/prometheus/api/v1/query_range -d 'query=histogram_quantile(1, sum(rate(aggregate_persist_time_bucket{kubernetes_namespace=~"prod", app="foo-service", appComponent=~"foo"}[5m])) by (aggregate_name, le))' -d 'start=1615977030' -d 'end=1615980630' -d 'step=30' -d 'nocache=1'
```

If results for this query are consistent over time, then the issue is related to response cache. The most likely reason for the issue is ingestion of data with old timestamps (aka backfilling). See [these docs](https://docs.victoriametrics.com/#backfilling) for details on how to deal with the issue.

The `nocache=1` query arg can be set up in [Grafana datasource](https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-settings) used for VictoriaMetrics at `custom query parameters` section.

2) Adding `deny_partial_response=1` query arg to the request to `/api/v1/query_range`. By default `vmselect` prefers returning partial responses if some of vmstorage nodes didn't return response due to any reason. Such responses are identified as partial with `is_partial:true` field inside response JSON. `vmselect` doesn't cache partial responses. This guarantees that `vmselect` continues serving incoming queries when some of `vmstorage` nodes are temporarily unavailable (e.g. `vmselect` prefers availability over consistency). This can be changed by passing `deny_partial_response=1` query arg to `/api/v1/query_range`. In this case `vmselect` returns error if at least one `vmstorage` node cannot return response for the incoming query. Example query with `deny_partial_response=1`:

```
curl http://vmselect:8481/select/0/prometheus/api/v1/query_range -d 'query=histogram_quantile(1, sum(rate(aggregate_persist_time_bucket{kubernetes_namespace=~"prod", app="foo-service", appComponent=~"foo"}[5m])) by (aggregate_name, le))' -d 'start=1615977030' -d 'end=1615980630' -d 'step=30' -d 'deny_partial_response=1'
```

If this query sometimes returns an error, then this means that some of `vmstorage` nodes periodically cannot serve requests for some reason. It is recommended investigating logs at `vmstorage` and `vmselect` nodes in order to identify the reason, which could lead to the error. The most frequent reason is too heavy query, which could result in either timeout or OOM (out of memory) crash at vmstorage node. See [this article](https://valyala.medium.com/how-to-optimize-promql-and-metricsql-queries-85a1b75bf986) on how to detect and optimize heavy PromQL and MetricsQL queries.

If `vmselect` continues returning different responses after performing steps above, then it would be great narrowing down the query, which returns incorrect results. E.g. removing the outer functions and adding more specific label filters in order to limit the number of time series the query needs to process. Then it would be great checking whether `vmselect` consistently returns the same set of raw samples for the selected time series on the selected time range. This can be done via [export API](https://docs.victoriametrics.com/#how-to-export-data-in-json-line-format).

**Comment by valyala** [comment]
`vmselect` should report errors returned from `vmstorage` nodes starting from [v1.73.1](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Previously such errors were suppressed by default unless `-search.denyPartialResponse` command-line flag is passed to `vmselect` (see [these docs](https://docs.victoriametrics.com/Cluster-VictoriaMetrics.html#cluster-availability) for more details). These errors must be returned to the caller instead of returning partial response, since these errors contain useful information on how to fix the error at `vmstorage` node. So, starting from `v1.73.1`, `vmselect` may return partial response only if some of vmstorage nodes are temporarily unreachable / unavailable (for instance, during `vmstorage` maintenance and/or upgrade).

**Comment by furkalor** [comment]
I faced the same issue. histogram_quantile function returns different values each time when I do a refresh of grafana dashboard. I use the next query to get data:

histogram_quantile﻿(﻿0.999﻿,﻿ ﻿sum﻿(﻿rate﻿(﻿http_request_duration_seconds_bucket﻿{﻿release﻿=﻿"$ReleaseType"﻿, ﻿status﻿=﻿"200"﻿,﻿path﻿!=﻿"/api/bi/ping"﻿}﻿)﻿)﻿ ﻿by﻿ ﻿(﻿le﻿)﻿)

Screenshot with an example of the graphic is attached. I use the latest version of victoriametrics cluster (1.77.1). Which kind of information should I provide to make it more clear?

![Screenshot_20220513_100754](https://user-images.githubusercontent.com/12525911/168231200-d2add6b3-2be5-45b0-8ae8-e4b82f3fe4e6.png)
![Screenshot_20220513_100733](https://user-images.githubusercontent.com/12525911/168231208-04b5d93c-58ff-476a-a03d-5948842bda76.png)

**Comment by hagen1778** [comment]
Hello @furkalor! Does the issue still remains for you? Can you try using the latest version of VictoriaMetrics which contains the following bugfix https://github.com/VictoriaMetrics/VictoriaMetrics/pull/3946

**Comment by hagen1778** [comment]
Closing the ticket as inactive.
