### ISSUE TITLE
VictoriaLogs Web UI: Cursor in log query input field randomly resets, mangling user input

### ISSUE THREAD

**Issue by Fusl** [VictoriaMetrics/VictoriaMetrics#7288]
### Describe the bug

When typing in the `Log query` input field in the VMUI for VictoriaLogs, the cursor position resets randomly during input, leading to mangled text. This issue occurs when the browser tab is resource-constrained or slow to respond, such as when displaying a large query result. For example, when typing `foo bar baz`, the input may become corrupted to `fooar baz b` as the cursor jumps to an earlier position mid-typing.

### To Reproduce

1. Query a large dataset with a high limit (e.g., 50,000 records).
2. Switch to table view
3. While the browser is displaying the result data, attempt to modify the query by typing at the end of the input (e.g., by keyboard smashing or quickly typing a Lorem Ipsum quote).
4. Observe that the cursor will intermittently reset to an earlier position, resulting in garbled text.

### Version

VictoriaLogs: victoria-logs-20241018-003518-tags-v0.37.0-victorialogs-0-g14e33d93ef
Chromium: Version 130.0.6723.58 (Official Build) Arch Linux (64-bit)

### Screenshots

![vmui.gif](https://github.com/user-attachments/assets/cab0ce86-53bb-46df-8b86-50795ea8d191)

### Additional information

This issue seems to be heavily related to browser resource limitations when handling displaying large query results, which slows down the responsiveness of the browser tab and causes the cursor in the log query input field to reset unexpectedly.

Used command to reproduce this issue as recorded in the GIF:
```sh
sleep 1; for letter in a b c d e f g h i j k l m n o p q r s t u v w x y z; do
echo type $letter
echo sleep 0.08
done | xdotool -
```

**Comment by valyala** [comment]
@Loori-R , is this issue already fixed in the commit dd89745a3402c0e18c1a4850fffb67de905520f3 ( pull request https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7294 ) ? If yes, then please close the issue, since this commit is included in [VictoriaLogs v0.38.0](https://docs.victoriametrics.com/victorialogs/changelog/)

**Comment by Fusl** [comment]
It's not, this is a different issue unfortunately.

**Comment by Fusl** [comment]
Here's an example of me trying to type `Action:="block"` while my browser is a little overwhelmed with displaying 2000 logs in the table view on `victoria-logs-20241030-223856-tags-v0.40.0-victorialogs-0-g1a7b55009b`:
![vmui](https://github.com/user-attachments/assets/4394e0b2-f752-4a78-b2cd-26d57197b788)

**Comment by Loori-R** [comment]
@valyala, commit dd89745 (pull request #7294) is not related to this issue.

**Comment by Loori-R** [comment]
FYI: commit [633a7e7245a709cf485583980eea70e17bd00f5c](https://github.com/VictoriaMetrics/VictoriaMetrics/commit/633a7e7245a709cf485583980eea70e17bd00f5c) reduces browser memory usage. It doesn't fix the bug but makes it happen less often.

**Comment by Fusl** [comment]
Fixed in https://github.com/VictoriaMetrics/VictoriaMetrics/pull/7861, thanks @Loori-R

**Comment by valyala** [comment]
FYI, the bugfix for this issue has been included in [v1.4.0-victorialogs](https://docs.victoriametrics.com/victorialogs/changelog/).
