### ISSUE TITLE
vmselect: inconsistent handling of NaNs during deduplication

### ISSUE THREAD

**Issue by tIGO** [VictoriaMetrics/VictoriaMetrics#7674]
### Describe the bug

During the evaluation of read query vmselect deduplicates samples using `dedupInterval` option. It picks the highest value across all points with the same timestamp next to the border of dedupInterval. The issue is any comparison with NaN via `<, >` returns false. This means that the position of NaN in `srcValues` could affect the result. 
Different vmselects produce different `srcValues` (at least because vmstorage connections are shuffled) so the output of query/range_query could flap on refresh.

### To Reproduce

Add testcases to `TestDeduplicateSamplesWithIdenticalTimestamps` 
```
  f(time.Second, []int64{1000, 2000, 2000}, []float64{1, 2, math.NaN()}, []int64{1000, 2000}, []float64{1, 2})
  f(time.Second, []int64{1000, 2000, 2000}, []float64{1, math.NaN(), 2}, []int64{1000, 2000}, []float64{1, 2})
```

### Version

Any version (e.g. 60d587f55b66842cd36d20a584f00c4e1128b1dc from master)

**Comment by f41gh7** [comment]
VictoriaMetrics doesn't store NaN values with the only exception as `Staleness markers`. Merge behavior for it described at documentation:

```
[Prometheus staleness markers](https://docs.victoriametrics.com/vmagent/#prometheus-staleness-markers) are processed as any other value during de-duplication. If raw sample with the biggest timestamp on -dedup.minScrapeInterval contains a stale marker, then it is kept after the deduplication. This allows properly preserving staleness markers during the de-duplication.
```

 https://docs.victoriametrics.com/#deduplication

**Comment by f41gh7** [comment]
Related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/5587

**Comment by tIGO** [comment]
I saw this issue, and it doesn't answer why the order matters and why vmselect should report different results. I prefer any consistent result.

**Comment by f41gh7** [comment]
I think this issue points to the actual bug with inconsistency for samples merge during deduplication for read. Which should be fixed. 

 And expected result of these test cases should be changed to :
```
 f(time.Second, []int64{1000, 2000, 2000}, []float64{1, 2, math.NaN()}, []int64{1000, 2000}, []float64{1, math.NaN()})
 f(time.Second, []int64{1000, 2000, 2000}, []float64{1, math.NaN(), 2}, []int64{1000, 2000}, []float64{1, math.NaN()})
```

 It makes query result consistent and preserve staleness markers as documentation describes. 

 FYI @hagen1778

**Comment by tIGO** [comment]
Initially, I did exactly this. But later, we thought there is no purpose in prioritizing NaN over real values in this case. If another agent has a non-NaN value in the current period, it will also report NaN in the next period.

**Comment by f41gh7** [comment]
> Initially, I did exactly this. But later, we thought there is no purpose in prioritizing NaN over real values in this case. If another agent has a non-NaN value in the current period, it will also report NaN in the next period.

And it must be handled by the query functions, that already take in account statelenss markers. 

 So the proper fix is to keep staleness markers.

**Comment by tIGO** [comment]
I've changed linked PR according to your logic (still don't get it though), please have a look.

**Comment by f41gh7** [comment]
> I've changed linked PR according to your logic (still don't get it though), please have a look.

  The most viable case for the logic to always keep staleness markers is de-duplication with an interval greater than `1ms`. 
 
 Consider the following example - configured `minDedupScrapeInterval=1m`, actual scrape interval is `5s`. In this case, all staleness markers will be lost. 

 Another example is `stale_samples_over_time` query function which must know about staleness markers.

**Comment by f41gh7** [comment]
The first part of the bugfix was included into [v1.108.0](https://docs.victoriametrics.com/changelog/#v11080), [v1.102.9](https://docs.victoriametrics.com/changelog/#v11029)  and [v1.97.14](https://docs.victoriametrics.com/changelog/#v19714)

**Comment by valyala** [comment]
See also the related issue https://github.com/VictoriaMetrics/VictoriaMetrics/issues/10196 . Regular values override staleness markers if they have the same timestamps starting from [v1.134.0](https://docs.victoriametrics.com/changelog/).
