### ISSUE TITLE
Increase() sometimes doesn't show increase for new series

### ISSUE THREAD

**Issue by raags** [VictoriaMetrics/VictoriaMetrics#962]
**Describe the bug**
In the screenshot below there are two metrics, `tests_foo` and `tests_bar` emitted as a counter (but constant) and scraped by `vmagent` every 15s. Then there is `increase()` function applied to both. The `tests_bar` metric shows the correct increase, but `tests_foo` does not.

![increase-mistmatch](https://user-images.githubusercontent.com/697714/102063029-8452f380-3e1b-11eb-9b01-e5e3a3e8d70a.png)

**To Reproduce**
Start two new series with non-zero counter value, and apply increase function.

**Expected behavior**
Consistent behaviour of Increase() taking the previous point as 0, and calculate the increase accordingly.

**Version**
```
# victoria-metrics-prod --version
victoria-metrics-20201205-115122-tags-v1.49.0-0-gae1db8fa0
```

**Used command-line flags**
```
/victoria-metrics-prod --storageDataPath=/vmdata --graphiteListenAddr=:2003 --httpListenAddr=:8428 -selfScrapeInterval=0
```

**Additional context**
Works fine when the previous data point is 0. I'm assuming this is related to the staleness handling, but all the samples have a constant scrape interval.

**Comment by raags** [comment]
Looks like a regression from this: https://github.com/VictoriaMetrics/VictoriaMetrics/issues/894 I'm not able to reproduce in v1.46.0

**Comment by valyala** [comment]
The issue must be fixed in the commit 11fa458e39175b01872848f5d6a273c620a2e264

**Comment by valyala** [comment]
The bugfix has been included in [v1.50.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases). Closing the issue as fixed.

@raags , feel free re-opening the issue if you notice related issues in `increase()` handling.

**Comment by raags** [comment]
@valyala Thanks, I'll test it. However, I didn't understand this from the changelog :

> BUGFIX: assume the previous value is 0 when calculating `increase()` for the first point on the graph **if its value doesn't exceed 100** and the delta between two first points equals to 0.

What does exceed 100 mean here?

**Comment by raags** [comment]
Its still happening:

![Screenshot 2020-12-15 at 7 55 58 PM](https://user-images.githubusercontent.com/697714/102227658-d5441400-3f0f-11eb-857e-97171db69c54.png)

test_foo1 doesn't show the increase but test_foo3 does

**Comment by valyala** [comment]
`increase()` should properly handle the following real-world cases:

* A counter starts with too big value. For example, a counter on the number of network packets such as `node_network_receive_packets_total` may start from big value when `node_exporter` is restarted, since the value is provided by the operating system and resets to zero only on operating system start.

* A single label changes in a counter metric. This is quite frequent case in Kubernetes setups. In this case the previous time series is substituted by a new time series with the initial value equal to the last value from the previous time series.

Users expect that `increase()` returns 0 for the first data point in both cases. VictoriaMetrics uses the following heuristics for differentiating these cases from the case when users expect the counter always start from 0:

* It compares the first value to the difference between the next value and the first value. If the first value exceeds 10x of the difference, then it assumes that the time series has been started from the first value instead of from zero. This heuristic covers quickly changed time series.

* When the difference between the first two data points equals to 0, then it is assumed that the time series starts from zero only if the first value doesn't exceed 100 . This heuristic covers big share of slowly changed time series with small deltas between adjacent data points.

I think `increase_pure()` function should be added without all the heuristics mentioned above, so it always returns the expected results for `pure` counters that always start from 0.

**Comment by belm0** [comment]
> When the difference between the first two data points equals to 0, then it is assumed that the time series starts from zero only if the first value doesn't exceed 100 . This heuristic covers big share of slowly changed time series with small deltas between adjacent data points.

@valyala I think this is making flawed assumptions about counter usage.

Counters are routinely used for counting bytes sent to storage or over a network, and certainly that is not slowly changing or small deltas.  Note that in Prometheus clients, counter `inc()` takes an optional delta, because we don't always increment by 1.  I don't think it's valid to make any assumption about magnitude.

This is a bandaid that will work for some people, for some cases, until it doesn't.  It doesn't give me confidence to rely on VM.

**Comment by belm0** [comment]
> A counter starts with too big value. For example, a counter on the number of network packets such as node_network_receive_packets_total may start from big value when node_exporter is restarted, since the value is provided by the operating system and resets to zero only on operating system start.

This is an incorrect use of counter.  Counters should not be used to relay values from other sources.  They should start at 0 when the prometheus client starts, and be incremented with new data since the time the client started.  Prometheus `increase()` and related infrastructure assume this.

**Comment by raags** [comment]
Yeah, these heuristics would lead to inconsistent and hard to understand behaviour. These issues stem for using a pull-based architecture, I don't see any way to work around them.

> Rather, please reserve `increase()` for the behaviour and counter intended use defined by Prometheus, and make a different function that has heuristics for dubious counter usage.

I feel the same, however, I prefer the behaviour of `increase()` which assumes pure counters. When plotting, these are readily visible as spikes and can be ignored depending on the context; as opposed to Prometheus which ignores these entirely.

**Comment by n9** [comment]
Should `increase()` return anything for the first value?

**Comment by raags** [comment]
I think it should, majority counters are not initialized/scrapped with initial value as zero. Consider a scenario, where a job comes up, does some work, increments counter and shutdown. The first increment almost always gets missed and throws off monitoring for us. 

For cases, where this can happen due to an exporter restart, I can handle them, as there are other metrics that can be checked to see if a restart happened.

**Comment by n9** [comment]
@raags Will your case work with "pure counters"?

**Comment by raags** [comment]
@n9 You mean the assumption that gaps in series are always considered by `increase()` to be a counter reset, then Yes. This is preferable to me than, a) Heuristics that are not consistent, b) Ignoring the first value entirely (unless it's zero). Because:
1. Exporter restarts can be determined by other indicators (gap in all metrics, `up` metric, uptime metric, etc). Also, scrape failures are rare, especially with vmagent HA mesh scraping. 
2. Alerts are anyways unaffected due to use of `For`
3. I'd rather have more data, that I can ignore/account for than not having any data.

**Comment by raags** [comment]
@valyala Any conclusion here? The `increase()` inconsistency is throwing off users. I prefer `increase()` that assumes a pure counter. Maybe have separate functions, or arguments such as `increase(q, pure=false)` and `increase(q, hearistics=true)`

**Comment by n9** [comment]
In case of separate functions or arguments, I think it should (also) support the option that it will return nothing for the first value to avoid peeks.

**Comment by belm0** [comment]
> > I think increase_pure() function should be added without all the heuristics mentioned above, so it always returns the expected results for pure counters that always start from 0.
>
> Rather, please reserve increase() for the behavior and counter intended use defined by Prometheus, and make a different function that has heuristics for dubious counter usage.

It's disappointing that `increase_pure()` was added.

We want to converge towards VictoriaMetrics having a good showing from Prometheus test suites.  Please leave the Prometheus functions as they're commonly understood when possible, and make new functions for significant departures...

**Comment by valyala** [comment]
> We want to converge towards VictoriaMetrics having a good showing from Prometheus test suites. Please leave the Prometheus functions as they're commonly understood when possible, and make new functions for significant departures...

I'm afraid the Promethes test suite isn't the best target to follow for MetricsQL. The reasons are [documented here](https://victoriametrics.github.io/MetricsQL.html).

Unfortunately, the `increase()` function in MetricsQL cannot be rolled back to Prometheus semantics, because VictoriaMetrics users rely on the current behavior.

The `increase_pure()` function has been added in [VictoriaMetrics v1.55.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases) because we received multiple requests from different users. It doesn't follow `increase()` semantics from Prometheus - it just returns the expected results for pure counters that always start from 0.

**Comment by valyala** [comment]
Closing the issue as done, since `increase_pure()` should cover the case described in the first message.
